// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: holistic_landmarks.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace HolisticPose {

  /// <summary>Holder for reflection information generated from holistic_landmarks.proto</summary>
  public static partial class HolisticLandmarksReflection {

    #region Descriptor
    /// <summary>File descriptor for holistic_landmarks.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static HolisticLandmarksReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chhob2xpc3RpY19sYW5kbWFya3MucHJvdG8SDGhvbGlzdGljUG9zZSI/CghM",
            "YW5kbWFyaxIJCgF4GAIgASgCEgkKAXkYAyABKAISCQoBehgEIAEoAhISCgpj",
            "b25maWRlbmNlGAYgASgCIugBChFIb2xpc3RpY0xhbmRtYXJrcxIyCg1wb3Nl",
            "TGFuZG1hcmtzGAEgASgLMhsuaG9saXN0aWNQb3NlLlBvc2VMYW5kbWFya3MS",
            "NgoRbGVmdEhhbmRMYW5kbWFya3MYAiABKAsyGy5ob2xpc3RpY1Bvc2UuSGFu",
            "ZExhbmRtYXJrcxI3ChJyaWdodEhhbmRMYW5kbWFya3MYAyABKAsyGy5ob2xp",
            "c3RpY1Bvc2UuSGFuZExhbmRtYXJrcxIuCgtmYWNlUmVzdWx0cxgEIAEoCzIZ",
            "LmhvbGlzdGljUG9zZS5GYWNlUmVzdWx0cyLgBAoNUG9zZUxhbmRtYXJrcxIp",
            "CglsYW5kbWFya3MYASADKAsyFi5ob2xpc3RpY1Bvc2UuTGFuZG1hcmsSDgoG",
            "bGVuZ3RoGAIgASgFIpMECg1MYW5kbWFya0luZGV4EggKBG5vc2UQABIQCgxs",
            "ZWZ0RXllSW5uZXIQARILCgdsZWZ0RXllEAISEAoMbGVmdEV5ZU91dGVyEAMS",
            "EQoNcmlnaHRFeWVJbm5lchAEEgwKCHJpZ2h0RXllEAUSEQoNcmlnaHRFeWVP",
            "dXRlchAGEgsKB2xlZnRFYXIQBxIMCghyaWdodEVhchAIEg0KCW1vdXRoTGVm",
            "dBAJEg4KCm1vdXRoUmlnaHQQChIQCgxsZWZ0U2hvdWxkZXIQCxIRCg1yaWdo",
            "dFNob3VsZGVyEAwSDQoJbGVmdEVsYm93EA0SDgoKcmlnaHRFbGJvdxAOEg0K",
            "CWxlZnRXcmlzdBAPEg4KCnJpZ2h0V3Jpc3QQEBINCglsZWZ0UGlua3kQERIO",
            "CgpyaWdodFBpbmt5EBISDQoJbGVmdEluZGV4EBMSDgoKcmlnaHRJbmRleBAU",
            "Eg0KCWxlZnRUaHVtYhAVEg4KCnJpZ2h0VGh1bWIQFhILCgdsZWZ0SGlwEBcS",
            "DAoIcmlnaHRIaXAQGBIMCghsZWZ0S25lZRAZEg0KCXJpZ2h0S25lZRAaEg0K",
            "CWxlZnRBbmtsZRAbEg4KCnJpZ2h0QW5rbGUQHBIMCghsZWZ0SGVlbBAdEg0K",
            "CXJpZ2h0SGVlbBAeEhEKDWxlZnRGb290SW5kZXgQHxISCg5yaWdodEZvb3RJ",
            "bmRleBAgIsYDCg1IYW5kTGFuZG1hcmtzEikKCWxhbmRtYXJrcxgBIAMoCzIW",
            "LmhvbGlzdGljUG9zZS5MYW5kbWFyaxIOCgZsZW5ndGgYAiABKAUi+QIKDUxh",
            "bmRtYXJrSW5kZXgSCQoFd3Jpc3QQABIMCgh0aHVtYkNNQxABEgwKCHRodW1i",
            "TUNQEAISCwoHdGh1bWJJUBADEgwKCHRodW1iVElQEAQSEgoOaW5kZXhGaW5n",
            "ZXJNQ1AQBRISCg5pbmRleEZpbmdlclBJUBAGEhIKDmluZGV4RmluZ2VyRElQ",
            "EAcSEgoOaW5kZXhGaW5nZXJUSVAQCBITCg9taWRkbGVGaW5nZXJNQ1AQCRIT",
            "Cg9taWRkbGVGaW5nZXJQSVAQChITCg9taWRkbGVGaW5nZXJESVAQCxITCg9t",
            "aWRkbGVGaW5nZXJUSVAQDBIRCg1yaW5nRmluZ2VyTUNQEA0SEQoNcmluZ0Zp",
            "bmdlclBJUBAOEhEKDXJpbmdGaW5nZXJESVAQDxIRCg1yaW5nRmluZ2VyVElQ",
            "EBASDAoIcGlua3lNQ1AQERIMCghwaW5reVBJUBASEgwKCHBpbmt5RElQEBMS",
            "DAoIcGlua3lUSVAQFCJ4CgtGYWNlUmVzdWx0cxIpCglsYW5kbWFya3MYASAD",
            "KAsyFi5ob2xpc3RpY1Bvc2UuTGFuZG1hcmsSLgoLYmxlbmRzaGFwZXMYAiAB",
            "KAsyGS5ob2xpc3RpY1Bvc2UuQmxlbmRzaGFwZXMSDgoGbGVuZ3RoGAMgASgF",
            "Ir4ICgtCbGVuZHNoYXBlcxIOCgZzY29yZXMYASADKAISDgoGbGVuZ3RoGAIg",
            "ASgFIo4IChBCbGVuZHNoYXBlc0luZGV4EgwKCF9uZXV0cmFsEAASEAoMYnJv",
            "d0Rvd25MZWZ0EAESEQoNYnJvd0Rvd25SaWdodBACEg8KC2Jyb3dJbm5lclVw",
            "EAMSEwoPYnJvd091dGVyVXBMZWZ0EAQSFAoQYnJvd091dGVyVXBSaWdodBAF",
            "Eg0KCWNoZWVrUHVmZhAGEhMKD2NoZWVrU3F1aW50TGVmdBAHEhQKEGNoZWVr",
            "U3F1aW50UmlnaHQQCBIQCgxleWVCbGlua0xlZnQQCRIRCg1leWVCbGlua1Jp",
            "Z2h0EAoSEwoPZXllTG9va0Rvd25MZWZ0EAsSFAoQZXllTG9va0Rvd25SaWdo",
            "dBAMEhEKDWV5ZUxvb2tJbkxlZnQQDRISCg5leWVMb29rSW5SaWdodBAOEhIK",
            "DmV5ZUxvb2tPdXRMZWZ0EA8SEwoPZXllTG9va091dFJpZ2h0EBASEQoNZXll",
            "TG9va1VwTGVmdBAREhIKDmV5ZUxvb2tVcFJpZ2h0EBISEQoNZXllU3F1aW50",
            "TGVmdBATEhIKDmV5ZVNxdWludFJpZ2h0EBQSDwoLZXllV2lkZUxlZnQQFRIQ",
            "CgxleWVXaWRlUmlnaHQQFhIOCgpqYXdGb3J3YXJkEBcSCwoHamF3TGVmdBAY",
            "EgsKB2phd09wZW4QGRIMCghqYXdSaWdodBAaEg4KCm1vdXRoQ2xvc2UQGxIT",
            "Cg9tb3V0aERpbXBsZUxlZnQQHBIUChBtb3V0aERpbXBsZVJpZ2h0EB0SEgoO",
            "bW91dGhGcm93bkxlZnQQHhITCg9tb3V0aEZyb3duUmlnaHQQHxIPCgttb3V0",
            "aEZ1bm5lbBAgEg0KCW1vdXRoTGVmdBAhEhYKEm1vdXRoTG93ZXJEb3duTGVm",
            "dBAiEhcKE21vdXRoTG93ZXJEb3duUmlnaHQQIxISCg5tb3V0aFByZXNzTGVm",
            "dBAkEhMKD21vdXRoUHJlc3NSaWdodBAlEg8KC21vdXRoUHVja2VyECYSDgoK",
            "bW91dGhSaWdodBAnEhIKDm1vdXRoUm9sbExvd2VyECgSEgoObW91dGhSb2xs",
            "VXBwZXIQKRITCg9tb3V0aFNocnVnTG93ZXIQKhITCg9tb3V0aFNocnVnVXBw",
            "ZXIQKxISCg5tb3V0aFNtaWxlTGVmdBAsEhMKD21vdXRoU21pbGVSaWdodBAt",
            "EhQKEG1vdXRoU3RyZXRjaExlZnQQLhIVChFtb3V0aFN0cmV0Y2hSaWdodBAv",
            "EhQKEG1vdXRoVXBwZXJVcExlZnQQMBIVChFtb3V0aFVwcGVyVXBSaWdodBAx",
            "EhEKDW5vc2VTbmVlckxlZnQQMhISCg5ub3NlU25lZXJSaWdodBAzEg0KCXRv",
            "bmd1ZU91dBA0YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::HolisticPose.Landmark), global::HolisticPose.Landmark.Parser, new[]{ "X", "Y", "Z", "Confidence" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HolisticPose.HolisticLandmarks), global::HolisticPose.HolisticLandmarks.Parser, new[]{ "PoseLandmarks", "LeftHandLandmarks", "RightHandLandmarks", "FaceResults" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HolisticPose.PoseLandmarks), global::HolisticPose.PoseLandmarks.Parser, new[]{ "Landmarks", "Length" }, null, new[]{ typeof(global::HolisticPose.PoseLandmarks.Types.LandmarkIndex) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HolisticPose.HandLandmarks), global::HolisticPose.HandLandmarks.Parser, new[]{ "Landmarks", "Length" }, null, new[]{ typeof(global::HolisticPose.HandLandmarks.Types.LandmarkIndex) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HolisticPose.FaceResults), global::HolisticPose.FaceResults.Parser, new[]{ "Landmarks", "Blendshapes", "Length" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HolisticPose.Blendshapes), global::HolisticPose.Blendshapes.Parser, new[]{ "Scores", "Length" }, null, new[]{ typeof(global::HolisticPose.Blendshapes.Types.BlendshapesIndex) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Landmark : pb::IMessage<Landmark>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Landmark> _parser = new pb::MessageParser<Landmark>(() => new Landmark());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Landmark> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HolisticPose.HolisticLandmarksReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Landmark() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Landmark(Landmark other) : this() {
      x_ = other.x_;
      y_ = other.y_;
      z_ = other.z_;
      confidence_ = other.confidence_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Landmark Clone() {
      return new Landmark(this);
    }

    /// <summary>Field number for the "x" field.</summary>
    public const int XFieldNumber = 2;
    private float x_;
    /// <summary>
    /// string name = 1;
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float X {
      get { return x_; }
      set {
        x_ = value;
      }
    }

    /// <summary>Field number for the "y" field.</summary>
    public const int YFieldNumber = 3;
    private float y_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Y {
      get { return y_; }
      set {
        y_ = value;
      }
    }

    /// <summary>Field number for the "z" field.</summary>
    public const int ZFieldNumber = 4;
    private float z_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Z {
      get { return z_; }
      set {
        z_ = value;
      }
    }

    /// <summary>Field number for the "confidence" field.</summary>
    public const int ConfidenceFieldNumber = 6;
    private float confidence_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Confidence {
      get { return confidence_; }
      set {
        confidence_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Landmark);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Landmark other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(X, other.X)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Y, other.Y)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Z, other.Z)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Confidence, other.Confidence)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (X != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(X);
      if (Y != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Y);
      if (Z != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Z);
      if (Confidence != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Confidence);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (X != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(X);
      }
      if (Y != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Y);
      }
      if (Z != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(Z);
      }
      if (Confidence != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(Confidence);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (X != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(X);
      }
      if (Y != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Y);
      }
      if (Z != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(Z);
      }
      if (Confidence != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(Confidence);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (X != 0F) {
        size += 1 + 4;
      }
      if (Y != 0F) {
        size += 1 + 4;
      }
      if (Z != 0F) {
        size += 1 + 4;
      }
      if (Confidence != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Landmark other) {
      if (other == null) {
        return;
      }
      if (other.X != 0F) {
        X = other.X;
      }
      if (other.Y != 0F) {
        Y = other.Y;
      }
      if (other.Z != 0F) {
        Z = other.Z;
      }
      if (other.Confidence != 0F) {
        Confidence = other.Confidence;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 21: {
            X = input.ReadFloat();
            break;
          }
          case 29: {
            Y = input.ReadFloat();
            break;
          }
          case 37: {
            Z = input.ReadFloat();
            break;
          }
          case 53: {
            Confidence = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 21: {
            X = input.ReadFloat();
            break;
          }
          case 29: {
            Y = input.ReadFloat();
            break;
          }
          case 37: {
            Z = input.ReadFloat();
            break;
          }
          case 53: {
            Confidence = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class HolisticLandmarks : pb::IMessage<HolisticLandmarks>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HolisticLandmarks> _parser = new pb::MessageParser<HolisticLandmarks>(() => new HolisticLandmarks());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HolisticLandmarks> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HolisticPose.HolisticLandmarksReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HolisticLandmarks() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HolisticLandmarks(HolisticLandmarks other) : this() {
      poseLandmarks_ = other.poseLandmarks_ != null ? other.poseLandmarks_.Clone() : null;
      leftHandLandmarks_ = other.leftHandLandmarks_ != null ? other.leftHandLandmarks_.Clone() : null;
      rightHandLandmarks_ = other.rightHandLandmarks_ != null ? other.rightHandLandmarks_.Clone() : null;
      faceResults_ = other.faceResults_ != null ? other.faceResults_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HolisticLandmarks Clone() {
      return new HolisticLandmarks(this);
    }

    /// <summary>Field number for the "poseLandmarks" field.</summary>
    public const int PoseLandmarksFieldNumber = 1;
    private global::HolisticPose.PoseLandmarks poseLandmarks_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HolisticPose.PoseLandmarks PoseLandmarks {
      get { return poseLandmarks_; }
      set {
        poseLandmarks_ = value;
      }
    }

    /// <summary>Field number for the "leftHandLandmarks" field.</summary>
    public const int LeftHandLandmarksFieldNumber = 2;
    private global::HolisticPose.HandLandmarks leftHandLandmarks_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HolisticPose.HandLandmarks LeftHandLandmarks {
      get { return leftHandLandmarks_; }
      set {
        leftHandLandmarks_ = value;
      }
    }

    /// <summary>Field number for the "rightHandLandmarks" field.</summary>
    public const int RightHandLandmarksFieldNumber = 3;
    private global::HolisticPose.HandLandmarks rightHandLandmarks_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HolisticPose.HandLandmarks RightHandLandmarks {
      get { return rightHandLandmarks_; }
      set {
        rightHandLandmarks_ = value;
      }
    }

    /// <summary>Field number for the "faceResults" field.</summary>
    public const int FaceResultsFieldNumber = 4;
    private global::HolisticPose.FaceResults faceResults_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HolisticPose.FaceResults FaceResults {
      get { return faceResults_; }
      set {
        faceResults_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HolisticLandmarks);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HolisticLandmarks other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(PoseLandmarks, other.PoseLandmarks)) return false;
      if (!object.Equals(LeftHandLandmarks, other.LeftHandLandmarks)) return false;
      if (!object.Equals(RightHandLandmarks, other.RightHandLandmarks)) return false;
      if (!object.Equals(FaceResults, other.FaceResults)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (poseLandmarks_ != null) hash ^= PoseLandmarks.GetHashCode();
      if (leftHandLandmarks_ != null) hash ^= LeftHandLandmarks.GetHashCode();
      if (rightHandLandmarks_ != null) hash ^= RightHandLandmarks.GetHashCode();
      if (faceResults_ != null) hash ^= FaceResults.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (poseLandmarks_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(PoseLandmarks);
      }
      if (leftHandLandmarks_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(LeftHandLandmarks);
      }
      if (rightHandLandmarks_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(RightHandLandmarks);
      }
      if (faceResults_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(FaceResults);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (poseLandmarks_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(PoseLandmarks);
      }
      if (leftHandLandmarks_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(LeftHandLandmarks);
      }
      if (rightHandLandmarks_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(RightHandLandmarks);
      }
      if (faceResults_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(FaceResults);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (poseLandmarks_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PoseLandmarks);
      }
      if (leftHandLandmarks_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LeftHandLandmarks);
      }
      if (rightHandLandmarks_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RightHandLandmarks);
      }
      if (faceResults_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FaceResults);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HolisticLandmarks other) {
      if (other == null) {
        return;
      }
      if (other.poseLandmarks_ != null) {
        if (poseLandmarks_ == null) {
          PoseLandmarks = new global::HolisticPose.PoseLandmarks();
        }
        PoseLandmarks.MergeFrom(other.PoseLandmarks);
      }
      if (other.leftHandLandmarks_ != null) {
        if (leftHandLandmarks_ == null) {
          LeftHandLandmarks = new global::HolisticPose.HandLandmarks();
        }
        LeftHandLandmarks.MergeFrom(other.LeftHandLandmarks);
      }
      if (other.rightHandLandmarks_ != null) {
        if (rightHandLandmarks_ == null) {
          RightHandLandmarks = new global::HolisticPose.HandLandmarks();
        }
        RightHandLandmarks.MergeFrom(other.RightHandLandmarks);
      }
      if (other.faceResults_ != null) {
        if (faceResults_ == null) {
          FaceResults = new global::HolisticPose.FaceResults();
        }
        FaceResults.MergeFrom(other.FaceResults);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (poseLandmarks_ == null) {
              PoseLandmarks = new global::HolisticPose.PoseLandmarks();
            }
            input.ReadMessage(PoseLandmarks);
            break;
          }
          case 18: {
            if (leftHandLandmarks_ == null) {
              LeftHandLandmarks = new global::HolisticPose.HandLandmarks();
            }
            input.ReadMessage(LeftHandLandmarks);
            break;
          }
          case 26: {
            if (rightHandLandmarks_ == null) {
              RightHandLandmarks = new global::HolisticPose.HandLandmarks();
            }
            input.ReadMessage(RightHandLandmarks);
            break;
          }
          case 34: {
            if (faceResults_ == null) {
              FaceResults = new global::HolisticPose.FaceResults();
            }
            input.ReadMessage(FaceResults);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (poseLandmarks_ == null) {
              PoseLandmarks = new global::HolisticPose.PoseLandmarks();
            }
            input.ReadMessage(PoseLandmarks);
            break;
          }
          case 18: {
            if (leftHandLandmarks_ == null) {
              LeftHandLandmarks = new global::HolisticPose.HandLandmarks();
            }
            input.ReadMessage(LeftHandLandmarks);
            break;
          }
          case 26: {
            if (rightHandLandmarks_ == null) {
              RightHandLandmarks = new global::HolisticPose.HandLandmarks();
            }
            input.ReadMessage(RightHandLandmarks);
            break;
          }
          case 34: {
            if (faceResults_ == null) {
              FaceResults = new global::HolisticPose.FaceResults();
            }
            input.ReadMessage(FaceResults);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class PoseLandmarks : pb::IMessage<PoseLandmarks>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PoseLandmarks> _parser = new pb::MessageParser<PoseLandmarks>(() => new PoseLandmarks());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PoseLandmarks> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HolisticPose.HolisticLandmarksReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PoseLandmarks() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PoseLandmarks(PoseLandmarks other) : this() {
      landmarks_ = other.landmarks_.Clone();
      length_ = other.length_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PoseLandmarks Clone() {
      return new PoseLandmarks(this);
    }

    /// <summary>Field number for the "landmarks" field.</summary>
    public const int LandmarksFieldNumber = 1;
    private static readonly pb::FieldCodec<global::HolisticPose.Landmark> _repeated_landmarks_codec
        = pb::FieldCodec.ForMessage(10, global::HolisticPose.Landmark.Parser);
    private readonly pbc::RepeatedField<global::HolisticPose.Landmark> landmarks_ = new pbc::RepeatedField<global::HolisticPose.Landmark>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::HolisticPose.Landmark> Landmarks {
      get { return landmarks_; }
    }

    /// <summary>Field number for the "length" field.</summary>
    public const int LengthFieldNumber = 2;
    private int length_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Length {
      get { return length_; }
      set {
        length_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PoseLandmarks);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PoseLandmarks other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!landmarks_.Equals(other.landmarks_)) return false;
      if (Length != other.Length) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= landmarks_.GetHashCode();
      if (Length != 0) hash ^= Length.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      landmarks_.WriteTo(output, _repeated_landmarks_codec);
      if (Length != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Length);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      landmarks_.WriteTo(ref output, _repeated_landmarks_codec);
      if (Length != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Length);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += landmarks_.CalculateSize(_repeated_landmarks_codec);
      if (Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Length);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PoseLandmarks other) {
      if (other == null) {
        return;
      }
      landmarks_.Add(other.landmarks_);
      if (other.Length != 0) {
        Length = other.Length;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            landmarks_.AddEntriesFrom(input, _repeated_landmarks_codec);
            break;
          }
          case 16: {
            Length = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            landmarks_.AddEntriesFrom(ref input, _repeated_landmarks_codec);
            break;
          }
          case 16: {
            Length = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the PoseLandmarks message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum LandmarkIndex {
        [pbr::OriginalName("nose")] Nose = 0,
        [pbr::OriginalName("leftEyeInner")] LeftEyeInner = 1,
        [pbr::OriginalName("leftEye")] LeftEye = 2,
        [pbr::OriginalName("leftEyeOuter")] LeftEyeOuter = 3,
        [pbr::OriginalName("rightEyeInner")] RightEyeInner = 4,
        [pbr::OriginalName("rightEye")] RightEye = 5,
        [pbr::OriginalName("rightEyeOuter")] RightEyeOuter = 6,
        [pbr::OriginalName("leftEar")] LeftEar = 7,
        [pbr::OriginalName("rightEar")] RightEar = 8,
        [pbr::OriginalName("mouthLeft")] MouthLeft = 9,
        [pbr::OriginalName("mouthRight")] MouthRight = 10,
        [pbr::OriginalName("leftShoulder")] LeftShoulder = 11,
        [pbr::OriginalName("rightShoulder")] RightShoulder = 12,
        [pbr::OriginalName("leftElbow")] LeftElbow = 13,
        [pbr::OriginalName("rightElbow")] RightElbow = 14,
        [pbr::OriginalName("leftWrist")] LeftWrist = 15,
        [pbr::OriginalName("rightWrist")] RightWrist = 16,
        [pbr::OriginalName("leftPinky")] LeftPinky = 17,
        [pbr::OriginalName("rightPinky")] RightPinky = 18,
        [pbr::OriginalName("leftIndex")] LeftIndex = 19,
        [pbr::OriginalName("rightIndex")] RightIndex = 20,
        [pbr::OriginalName("leftThumb")] LeftThumb = 21,
        [pbr::OriginalName("rightThumb")] RightThumb = 22,
        [pbr::OriginalName("leftHip")] LeftHip = 23,
        [pbr::OriginalName("rightHip")] RightHip = 24,
        [pbr::OriginalName("leftKnee")] LeftKnee = 25,
        [pbr::OriginalName("rightKnee")] RightKnee = 26,
        [pbr::OriginalName("leftAnkle")] LeftAnkle = 27,
        [pbr::OriginalName("rightAnkle")] RightAnkle = 28,
        [pbr::OriginalName("leftHeel")] LeftHeel = 29,
        [pbr::OriginalName("rightHeel")] RightHeel = 30,
        [pbr::OriginalName("leftFootIndex")] LeftFootIndex = 31,
        [pbr::OriginalName("rightFootIndex")] RightFootIndex = 32,
      }

    }
    #endregion

  }

  public sealed partial class HandLandmarks : pb::IMessage<HandLandmarks>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HandLandmarks> _parser = new pb::MessageParser<HandLandmarks>(() => new HandLandmarks());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HandLandmarks> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HolisticPose.HolisticLandmarksReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HandLandmarks() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HandLandmarks(HandLandmarks other) : this() {
      landmarks_ = other.landmarks_.Clone();
      length_ = other.length_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HandLandmarks Clone() {
      return new HandLandmarks(this);
    }

    /// <summary>Field number for the "landmarks" field.</summary>
    public const int LandmarksFieldNumber = 1;
    private static readonly pb::FieldCodec<global::HolisticPose.Landmark> _repeated_landmarks_codec
        = pb::FieldCodec.ForMessage(10, global::HolisticPose.Landmark.Parser);
    private readonly pbc::RepeatedField<global::HolisticPose.Landmark> landmarks_ = new pbc::RepeatedField<global::HolisticPose.Landmark>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::HolisticPose.Landmark> Landmarks {
      get { return landmarks_; }
    }

    /// <summary>Field number for the "length" field.</summary>
    public const int LengthFieldNumber = 2;
    private int length_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Length {
      get { return length_; }
      set {
        length_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HandLandmarks);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HandLandmarks other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!landmarks_.Equals(other.landmarks_)) return false;
      if (Length != other.Length) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= landmarks_.GetHashCode();
      if (Length != 0) hash ^= Length.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      landmarks_.WriteTo(output, _repeated_landmarks_codec);
      if (Length != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Length);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      landmarks_.WriteTo(ref output, _repeated_landmarks_codec);
      if (Length != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Length);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += landmarks_.CalculateSize(_repeated_landmarks_codec);
      if (Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Length);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HandLandmarks other) {
      if (other == null) {
        return;
      }
      landmarks_.Add(other.landmarks_);
      if (other.Length != 0) {
        Length = other.Length;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            landmarks_.AddEntriesFrom(input, _repeated_landmarks_codec);
            break;
          }
          case 16: {
            Length = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            landmarks_.AddEntriesFrom(ref input, _repeated_landmarks_codec);
            break;
          }
          case 16: {
            Length = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the HandLandmarks message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum LandmarkIndex {
        [pbr::OriginalName("wrist")] Wrist = 0,
        [pbr::OriginalName("thumbCMC")] ThumbCmc = 1,
        [pbr::OriginalName("thumbMCP")] ThumbMcp = 2,
        [pbr::OriginalName("thumbIP")] ThumbIp = 3,
        [pbr::OriginalName("thumbTIP")] ThumbTip = 4,
        [pbr::OriginalName("indexFingerMCP")] IndexFingerMcp = 5,
        [pbr::OriginalName("indexFingerPIP")] IndexFingerPip = 6,
        [pbr::OriginalName("indexFingerDIP")] IndexFingerDip = 7,
        [pbr::OriginalName("indexFingerTIP")] IndexFingerTip = 8,
        [pbr::OriginalName("middleFingerMCP")] MiddleFingerMcp = 9,
        [pbr::OriginalName("middleFingerPIP")] MiddleFingerPip = 10,
        [pbr::OriginalName("middleFingerDIP")] MiddleFingerDip = 11,
        [pbr::OriginalName("middleFingerTIP")] MiddleFingerTip = 12,
        [pbr::OriginalName("ringFingerMCP")] RingFingerMcp = 13,
        [pbr::OriginalName("ringFingerPIP")] RingFingerPip = 14,
        [pbr::OriginalName("ringFingerDIP")] RingFingerDip = 15,
        [pbr::OriginalName("ringFingerTIP")] RingFingerTip = 16,
        [pbr::OriginalName("pinkyMCP")] PinkyMcp = 17,
        [pbr::OriginalName("pinkyPIP")] PinkyPip = 18,
        [pbr::OriginalName("pinkyDIP")] PinkyDip = 19,
        [pbr::OriginalName("pinkyTIP")] PinkyTip = 20,
      }

    }
    #endregion

  }

  public sealed partial class FaceResults : pb::IMessage<FaceResults>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FaceResults> _parser = new pb::MessageParser<FaceResults>(() => new FaceResults());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FaceResults> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HolisticPose.HolisticLandmarksReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FaceResults() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FaceResults(FaceResults other) : this() {
      landmarks_ = other.landmarks_.Clone();
      blendshapes_ = other.blendshapes_ != null ? other.blendshapes_.Clone() : null;
      length_ = other.length_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FaceResults Clone() {
      return new FaceResults(this);
    }

    /// <summary>Field number for the "landmarks" field.</summary>
    public const int LandmarksFieldNumber = 1;
    private static readonly pb::FieldCodec<global::HolisticPose.Landmark> _repeated_landmarks_codec
        = pb::FieldCodec.ForMessage(10, global::HolisticPose.Landmark.Parser);
    private readonly pbc::RepeatedField<global::HolisticPose.Landmark> landmarks_ = new pbc::RepeatedField<global::HolisticPose.Landmark>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::HolisticPose.Landmark> Landmarks {
      get { return landmarks_; }
    }

    /// <summary>Field number for the "blendshapes" field.</summary>
    public const int BlendshapesFieldNumber = 2;
    private global::HolisticPose.Blendshapes blendshapes_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HolisticPose.Blendshapes Blendshapes {
      get { return blendshapes_; }
      set {
        blendshapes_ = value;
      }
    }

    /// <summary>Field number for the "length" field.</summary>
    public const int LengthFieldNumber = 3;
    private int length_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Length {
      get { return length_; }
      set {
        length_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FaceResults);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FaceResults other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!landmarks_.Equals(other.landmarks_)) return false;
      if (!object.Equals(Blendshapes, other.Blendshapes)) return false;
      if (Length != other.Length) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= landmarks_.GetHashCode();
      if (blendshapes_ != null) hash ^= Blendshapes.GetHashCode();
      if (Length != 0) hash ^= Length.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      landmarks_.WriteTo(output, _repeated_landmarks_codec);
      if (blendshapes_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Blendshapes);
      }
      if (Length != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Length);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      landmarks_.WriteTo(ref output, _repeated_landmarks_codec);
      if (blendshapes_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Blendshapes);
      }
      if (Length != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Length);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += landmarks_.CalculateSize(_repeated_landmarks_codec);
      if (blendshapes_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Blendshapes);
      }
      if (Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Length);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FaceResults other) {
      if (other == null) {
        return;
      }
      landmarks_.Add(other.landmarks_);
      if (other.blendshapes_ != null) {
        if (blendshapes_ == null) {
          Blendshapes = new global::HolisticPose.Blendshapes();
        }
        Blendshapes.MergeFrom(other.Blendshapes);
      }
      if (other.Length != 0) {
        Length = other.Length;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            landmarks_.AddEntriesFrom(input, _repeated_landmarks_codec);
            break;
          }
          case 18: {
            if (blendshapes_ == null) {
              Blendshapes = new global::HolisticPose.Blendshapes();
            }
            input.ReadMessage(Blendshapes);
            break;
          }
          case 24: {
            Length = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            landmarks_.AddEntriesFrom(ref input, _repeated_landmarks_codec);
            break;
          }
          case 18: {
            if (blendshapes_ == null) {
              Blendshapes = new global::HolisticPose.Blendshapes();
            }
            input.ReadMessage(Blendshapes);
            break;
          }
          case 24: {
            Length = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Blendshapes : pb::IMessage<Blendshapes>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Blendshapes> _parser = new pb::MessageParser<Blendshapes>(() => new Blendshapes());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Blendshapes> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HolisticPose.HolisticLandmarksReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Blendshapes() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Blendshapes(Blendshapes other) : this() {
      scores_ = other.scores_.Clone();
      length_ = other.length_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Blendshapes Clone() {
      return new Blendshapes(this);
    }

    /// <summary>Field number for the "scores" field.</summary>
    public const int ScoresFieldNumber = 1;
    private static readonly pb::FieldCodec<float> _repeated_scores_codec
        = pb::FieldCodec.ForFloat(10);
    private readonly pbc::RepeatedField<float> scores_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> Scores {
      get { return scores_; }
    }

    /// <summary>Field number for the "length" field.</summary>
    public const int LengthFieldNumber = 2;
    private int length_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Length {
      get { return length_; }
      set {
        length_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Blendshapes);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Blendshapes other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!scores_.Equals(other.scores_)) return false;
      if (Length != other.Length) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= scores_.GetHashCode();
      if (Length != 0) hash ^= Length.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      scores_.WriteTo(output, _repeated_scores_codec);
      if (Length != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Length);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      scores_.WriteTo(ref output, _repeated_scores_codec);
      if (Length != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Length);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += scores_.CalculateSize(_repeated_scores_codec);
      if (Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Length);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Blendshapes other) {
      if (other == null) {
        return;
      }
      scores_.Add(other.scores_);
      if (other.Length != 0) {
        Length = other.Length;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 13: {
            scores_.AddEntriesFrom(input, _repeated_scores_codec);
            break;
          }
          case 16: {
            Length = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10:
          case 13: {
            scores_.AddEntriesFrom(ref input, _repeated_scores_codec);
            break;
          }
          case 16: {
            Length = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Blendshapes message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum BlendshapesIndex {
        [pbr::OriginalName("_neutral")] Neutral = 0,
        [pbr::OriginalName("browDownLeft")] BrowDownLeft = 1,
        [pbr::OriginalName("browDownRight")] BrowDownRight = 2,
        [pbr::OriginalName("browInnerUp")] BrowInnerUp = 3,
        [pbr::OriginalName("browOuterUpLeft")] BrowOuterUpLeft = 4,
        [pbr::OriginalName("browOuterUpRight")] BrowOuterUpRight = 5,
        [pbr::OriginalName("cheekPuff")] CheekPuff = 6,
        [pbr::OriginalName("cheekSquintLeft")] CheekSquintLeft = 7,
        [pbr::OriginalName("cheekSquintRight")] CheekSquintRight = 8,
        [pbr::OriginalName("eyeBlinkLeft")] EyeBlinkLeft = 9,
        [pbr::OriginalName("eyeBlinkRight")] EyeBlinkRight = 10,
        [pbr::OriginalName("eyeLookDownLeft")] EyeLookDownLeft = 11,
        [pbr::OriginalName("eyeLookDownRight")] EyeLookDownRight = 12,
        [pbr::OriginalName("eyeLookInLeft")] EyeLookInLeft = 13,
        [pbr::OriginalName("eyeLookInRight")] EyeLookInRight = 14,
        [pbr::OriginalName("eyeLookOutLeft")] EyeLookOutLeft = 15,
        [pbr::OriginalName("eyeLookOutRight")] EyeLookOutRight = 16,
        [pbr::OriginalName("eyeLookUpLeft")] EyeLookUpLeft = 17,
        [pbr::OriginalName("eyeLookUpRight")] EyeLookUpRight = 18,
        [pbr::OriginalName("eyeSquintLeft")] EyeSquintLeft = 19,
        [pbr::OriginalName("eyeSquintRight")] EyeSquintRight = 20,
        [pbr::OriginalName("eyeWideLeft")] EyeWideLeft = 21,
        [pbr::OriginalName("eyeWideRight")] EyeWideRight = 22,
        [pbr::OriginalName("jawForward")] JawForward = 23,
        [pbr::OriginalName("jawLeft")] JawLeft = 24,
        [pbr::OriginalName("jawOpen")] JawOpen = 25,
        [pbr::OriginalName("jawRight")] JawRight = 26,
        [pbr::OriginalName("mouthClose")] MouthClose = 27,
        [pbr::OriginalName("mouthDimpleLeft")] MouthDimpleLeft = 28,
        [pbr::OriginalName("mouthDimpleRight")] MouthDimpleRight = 29,
        [pbr::OriginalName("mouthFrownLeft")] MouthFrownLeft = 30,
        [pbr::OriginalName("mouthFrownRight")] MouthFrownRight = 31,
        [pbr::OriginalName("mouthFunnel")] MouthFunnel = 32,
        [pbr::OriginalName("mouthLeft")] MouthLeft = 33,
        [pbr::OriginalName("mouthLowerDownLeft")] MouthLowerDownLeft = 34,
        [pbr::OriginalName("mouthLowerDownRight")] MouthLowerDownRight = 35,
        [pbr::OriginalName("mouthPressLeft")] MouthPressLeft = 36,
        [pbr::OriginalName("mouthPressRight")] MouthPressRight = 37,
        [pbr::OriginalName("mouthPucker")] MouthPucker = 38,
        [pbr::OriginalName("mouthRight")] MouthRight = 39,
        [pbr::OriginalName("mouthRollLower")] MouthRollLower = 40,
        [pbr::OriginalName("mouthRollUpper")] MouthRollUpper = 41,
        [pbr::OriginalName("mouthShrugLower")] MouthShrugLower = 42,
        [pbr::OriginalName("mouthShrugUpper")] MouthShrugUpper = 43,
        [pbr::OriginalName("mouthSmileLeft")] MouthSmileLeft = 44,
        [pbr::OriginalName("mouthSmileRight")] MouthSmileRight = 45,
        [pbr::OriginalName("mouthStretchLeft")] MouthStretchLeft = 46,
        [pbr::OriginalName("mouthStretchRight")] MouthStretchRight = 47,
        [pbr::OriginalName("mouthUpperUpLeft")] MouthUpperUpLeft = 48,
        [pbr::OriginalName("mouthUpperUpRight")] MouthUpperUpRight = 49,
        [pbr::OriginalName("noseSneerLeft")] NoseSneerLeft = 50,
        [pbr::OriginalName("noseSneerRight")] NoseSneerRight = 51,
        [pbr::OriginalName("tongueOut")] TongueOut = 52,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
