// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: src/proto/holistic_landmarks.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace HolisticPose {

  /// <summary>Holder for reflection information generated from src/proto/holistic_landmarks.proto</summary>
  public static partial class HolisticLandmarksReflection {

    #region Descriptor
    /// <summary>File descriptor for src/proto/holistic_landmarks.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static HolisticLandmarksReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiJzcmMvcHJvdG8vaG9saXN0aWNfbGFuZG1hcmtzLnByb3RvEgxob2xpc3Rp",
            "Y1Bvc2UiPwoITGFuZG1hcmsSCQoBeBgCIAEoAhIJCgF5GAMgASgCEgkKAXoY",
            "BCABKAISEgoKY29uZmlkZW5jZRgGIAEoAiLoAQoRSG9saXN0aWNMYW5kbWFy",
            "a3MSMgoNcG9zZUxhbmRtYXJrcxgBIAEoCzIbLmhvbGlzdGljUG9zZS5Qb3Nl",
            "TGFuZG1hcmtzEjYKEWxlZnRIYW5kTGFuZG1hcmtzGAIgASgLMhsuaG9saXN0",
            "aWNQb3NlLkhhbmRMYW5kbWFya3MSNwoScmlnaHRIYW5kTGFuZG1hcmtzGAMg",
            "ASgLMhsuaG9saXN0aWNQb3NlLkhhbmRMYW5kbWFya3MSLgoLZmFjZVJlc3Vs",
            "dHMYBCABKAsyGS5ob2xpc3RpY1Bvc2UuRmFjZVJlc3VsdHMi0AQKDVBvc2VM",
            "YW5kbWFya3MSKQoJbGFuZG1hcmtzGAEgAygLMhYuaG9saXN0aWNQb3NlLkxh",
            "bmRtYXJrIpMECg1MYW5kbWFya0luZGV4EggKBG5vc2UQABIQCgxsZWZ0RXll",
            "SW5uZXIQARILCgdsZWZ0RXllEAISEAoMbGVmdEV5ZU91dGVyEAMSEQoNcmln",
            "aHRFeWVJbm5lchAEEgwKCHJpZ2h0RXllEAUSEQoNcmlnaHRFeWVPdXRlchAG",
            "EgsKB2xlZnRFYXIQBxIMCghyaWdodEVhchAIEg0KCW1vdXRoTGVmdBAJEg4K",
            "Cm1vdXRoUmlnaHQQChIQCgxsZWZ0U2hvdWxkZXIQCxIRCg1yaWdodFNob3Vs",
            "ZGVyEAwSDQoJbGVmdEVsYm93EA0SDgoKcmlnaHRFbGJvdxAOEg0KCWxlZnRX",
            "cmlzdBAPEg4KCnJpZ2h0V3Jpc3QQEBINCglsZWZ0UGlua3kQERIOCgpyaWdo",
            "dFBpbmt5EBISDQoJbGVmdEluZGV4EBMSDgoKcmlnaHRJbmRleBAUEg0KCWxl",
            "ZnRUaHVtYhAVEg4KCnJpZ2h0VGh1bWIQFhILCgdsZWZ0SGlwEBcSDAoIcmln",
            "aHRIaXAQGBIMCghsZWZ0S25lZRAZEg0KCXJpZ2h0S25lZRAaEg0KCWxlZnRB",
            "bmtsZRAbEg4KCnJpZ2h0QW5rbGUQHBIMCghsZWZ0SGVlbBAdEg0KCXJpZ2h0",
            "SGVlbBAeEhEKDWxlZnRGb290SW5kZXgQHxISCg5yaWdodEZvb3RJbmRleBAg",
            "IrYDCg1IYW5kTGFuZG1hcmtzEikKCWxhbmRtYXJrcxgBIAMoCzIWLmhvbGlz",
            "dGljUG9zZS5MYW5kbWFyayL5AgoNTGFuZG1hcmtJbmRleBIJCgV3cmlzdBAA",
            "EgwKCHRodW1iQ01DEAESDAoIdGh1bWJNQ1AQAhILCgd0aHVtYklQEAMSDAoI",
            "dGh1bWJUSVAQBBISCg5pbmRleEZpbmdlck1DUBAFEhIKDmluZGV4RmluZ2Vy",
            "UElQEAYSEgoOaW5kZXhGaW5nZXJESVAQBxISCg5pbmRleEZpbmdlclRJUBAI",
            "EhMKD21pZGRsZUZpbmdlck1DUBAJEhMKD21pZGRsZUZpbmdlclBJUBAKEhMK",
            "D21pZGRsZUZpbmdlckRJUBALEhMKD21pZGRsZUZpbmdlclRJUBAMEhEKDXJp",
            "bmdGaW5nZXJNQ1AQDRIRCg1yaW5nRmluZ2VyUElQEA4SEQoNcmluZ0Zpbmdl",
            "ckRJUBAPEhEKDXJpbmdGaW5nZXJUSVAQEBIMCghwaW5reU1DUBAREgwKCHBp",
            "bmt5UElQEBISDAoIcGlua3lESVAQExIMCghwaW5reVRJUBAUImgKC0ZhY2VS",
            "ZXN1bHRzEikKCWxhbmRtYXJrcxgBIAMoCzIWLmhvbGlzdGljUG9zZS5MYW5k",
            "bWFyaxIuCgtibGVuZHNoYXBlcxgCIAEoCzIZLmhvbGlzdGljUG9zZS5CbGVu",
            "ZHNoYXBlcyKuCAoLQmxlbmRzaGFwZXMSDgoGc2NvcmVzGAEgAygCIo4IChBC",
            "bGVuZHNoYXBlc0luZGV4EgwKCF9uZXV0cmFsEAASEAoMYnJvd0Rvd25MZWZ0",
            "EAESEQoNYnJvd0Rvd25SaWdodBACEg8KC2Jyb3dJbm5lclVwEAMSEwoPYnJv",
            "d091dGVyVXBMZWZ0EAQSFAoQYnJvd091dGVyVXBSaWdodBAFEg0KCWNoZWVr",
            "UHVmZhAGEhMKD2NoZWVrU3F1aW50TGVmdBAHEhQKEGNoZWVrU3F1aW50Umln",
            "aHQQCBIQCgxleWVCbGlua0xlZnQQCRIRCg1leWVCbGlua1JpZ2h0EAoSEwoP",
            "ZXllTG9va0Rvd25MZWZ0EAsSFAoQZXllTG9va0Rvd25SaWdodBAMEhEKDWV5",
            "ZUxvb2tJbkxlZnQQDRISCg5leWVMb29rSW5SaWdodBAOEhIKDmV5ZUxvb2tP",
            "dXRMZWZ0EA8SEwoPZXllTG9va091dFJpZ2h0EBASEQoNZXllTG9va1VwTGVm",
            "dBAREhIKDmV5ZUxvb2tVcFJpZ2h0EBISEQoNZXllU3F1aW50TGVmdBATEhIK",
            "DmV5ZVNxdWludFJpZ2h0EBQSDwoLZXllV2lkZUxlZnQQFRIQCgxleWVXaWRl",
            "UmlnaHQQFhIOCgpqYXdGb3J3YXJkEBcSCwoHamF3TGVmdBAYEgsKB2phd09w",
            "ZW4QGRIMCghqYXdSaWdodBAaEg4KCm1vdXRoQ2xvc2UQGxITCg9tb3V0aERp",
            "bXBsZUxlZnQQHBIUChBtb3V0aERpbXBsZVJpZ2h0EB0SEgoObW91dGhGcm93",
            "bkxlZnQQHhITCg9tb3V0aEZyb3duUmlnaHQQHxIPCgttb3V0aEZ1bm5lbBAg",
            "Eg0KCW1vdXRoTGVmdBAhEhYKEm1vdXRoTG93ZXJEb3duTGVmdBAiEhcKE21v",
            "dXRoTG93ZXJEb3duUmlnaHQQIxISCg5tb3V0aFByZXNzTGVmdBAkEhMKD21v",
            "dXRoUHJlc3NSaWdodBAlEg8KC21vdXRoUHVja2VyECYSDgoKbW91dGhSaWdo",
            "dBAnEhIKDm1vdXRoUm9sbExvd2VyECgSEgoObW91dGhSb2xsVXBwZXIQKRIT",
            "Cg9tb3V0aFNocnVnTG93ZXIQKhITCg9tb3V0aFNocnVnVXBwZXIQKxISCg5t",
            "b3V0aFNtaWxlTGVmdBAsEhMKD21vdXRoU21pbGVSaWdodBAtEhQKEG1vdXRo",
            "U3RyZXRjaExlZnQQLhIVChFtb3V0aFN0cmV0Y2hSaWdodBAvEhQKEG1vdXRo",
            "VXBwZXJVcExlZnQQMBIVChFtb3V0aFVwcGVyVXBSaWdodBAxEhEKDW5vc2VT",
            "bmVlckxlZnQQMhISCg5ub3NlU25lZXJSaWdodBAzEg0KCXRvbmd1ZU91dBA0",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::HolisticPose.Landmark), global::HolisticPose.Landmark.Parser, new[]{ "X", "Y", "Z", "Confidence" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HolisticPose.HolisticLandmarks), global::HolisticPose.HolisticLandmarks.Parser, new[]{ "PoseLandmarks", "LeftHandLandmarks", "RightHandLandmarks", "FaceResults" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HolisticPose.PoseLandmarks), global::HolisticPose.PoseLandmarks.Parser, new[]{ "Landmarks" }, null, new[]{ typeof(global::HolisticPose.PoseLandmarks.Types.LandmarkIndex) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HolisticPose.HandLandmarks), global::HolisticPose.HandLandmarks.Parser, new[]{ "Landmarks" }, null, new[]{ typeof(global::HolisticPose.HandLandmarks.Types.LandmarkIndex) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HolisticPose.FaceResults), global::HolisticPose.FaceResults.Parser, new[]{ "Landmarks", "Blendshapes" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HolisticPose.Blendshapes), global::HolisticPose.Blendshapes.Parser, new[]{ "Scores" }, null, new[]{ typeof(global::HolisticPose.Blendshapes.Types.BlendshapesIndex) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Landmark : pb::IMessage<Landmark>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Landmark> _parser = new pb::MessageParser<Landmark>(() => new Landmark());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Landmark> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HolisticPose.HolisticLandmarksReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Landmark() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Landmark(Landmark other) : this() {
      x_ = other.x_;
      y_ = other.y_;
      z_ = other.z_;
      confidence_ = other.confidence_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Landmark Clone() {
      return new Landmark(this);
    }

    /// <summary>Field number for the "x" field.</summary>
    public const int XFieldNumber = 2;
    private float x_;
    /// <summary>
    /// string name = 1;
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float X {
      get { return x_; }
      set {
        x_ = value;
      }
    }

    /// <summary>Field number for the "y" field.</summary>
    public const int YFieldNumber = 3;
    private float y_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Y {
      get { return y_; }
      set {
        y_ = value;
      }
    }

    /// <summary>Field number for the "z" field.</summary>
    public const int ZFieldNumber = 4;
    private float z_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Z {
      get { return z_; }
      set {
        z_ = value;
      }
    }

    /// <summary>Field number for the "confidence" field.</summary>
    public const int ConfidenceFieldNumber = 6;
    private float confidence_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Confidence {
      get { return confidence_; }
      set {
        confidence_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Landmark);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Landmark other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(X, other.X)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Y, other.Y)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Z, other.Z)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Confidence, other.Confidence)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (X != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(X);
      if (Y != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Y);
      if (Z != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Z);
      if (Confidence != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Confidence);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (X != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(X);
      }
      if (Y != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Y);
      }
      if (Z != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(Z);
      }
      if (Confidence != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(Confidence);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (X != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(X);
      }
      if (Y != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Y);
      }
      if (Z != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(Z);
      }
      if (Confidence != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(Confidence);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (X != 0F) {
        size += 1 + 4;
      }
      if (Y != 0F) {
        size += 1 + 4;
      }
      if (Z != 0F) {
        size += 1 + 4;
      }
      if (Confidence != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Landmark other) {
      if (other == null) {
        return;
      }
      if (other.X != 0F) {
        X = other.X;
      }
      if (other.Y != 0F) {
        Y = other.Y;
      }
      if (other.Z != 0F) {
        Z = other.Z;
      }
      if (other.Confidence != 0F) {
        Confidence = other.Confidence;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 21: {
            X = input.ReadFloat();
            break;
          }
          case 29: {
            Y = input.ReadFloat();
            break;
          }
          case 37: {
            Z = input.ReadFloat();
            break;
          }
          case 53: {
            Confidence = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 21: {
            X = input.ReadFloat();
            break;
          }
          case 29: {
            Y = input.ReadFloat();
            break;
          }
          case 37: {
            Z = input.ReadFloat();
            break;
          }
          case 53: {
            Confidence = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class HolisticLandmarks : pb::IMessage<HolisticLandmarks>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HolisticLandmarks> _parser = new pb::MessageParser<HolisticLandmarks>(() => new HolisticLandmarks());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HolisticLandmarks> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HolisticPose.HolisticLandmarksReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HolisticLandmarks() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HolisticLandmarks(HolisticLandmarks other) : this() {
      poseLandmarks_ = other.poseLandmarks_ != null ? other.poseLandmarks_.Clone() : null;
      leftHandLandmarks_ = other.leftHandLandmarks_ != null ? other.leftHandLandmarks_.Clone() : null;
      rightHandLandmarks_ = other.rightHandLandmarks_ != null ? other.rightHandLandmarks_.Clone() : null;
      faceResults_ = other.faceResults_ != null ? other.faceResults_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HolisticLandmarks Clone() {
      return new HolisticLandmarks(this);
    }

    /// <summary>Field number for the "poseLandmarks" field.</summary>
    public const int PoseLandmarksFieldNumber = 1;
    private global::HolisticPose.PoseLandmarks poseLandmarks_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HolisticPose.PoseLandmarks PoseLandmarks {
      get { return poseLandmarks_; }
      set {
        poseLandmarks_ = value;
      }
    }

    /// <summary>Field number for the "leftHandLandmarks" field.</summary>
    public const int LeftHandLandmarksFieldNumber = 2;
    private global::HolisticPose.HandLandmarks leftHandLandmarks_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HolisticPose.HandLandmarks LeftHandLandmarks {
      get { return leftHandLandmarks_; }
      set {
        leftHandLandmarks_ = value;
      }
    }

    /// <summary>Field number for the "rightHandLandmarks" field.</summary>
    public const int RightHandLandmarksFieldNumber = 3;
    private global::HolisticPose.HandLandmarks rightHandLandmarks_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HolisticPose.HandLandmarks RightHandLandmarks {
      get { return rightHandLandmarks_; }
      set {
        rightHandLandmarks_ = value;
      }
    }

    /// <summary>Field number for the "faceResults" field.</summary>
    public const int FaceResultsFieldNumber = 4;
    private global::HolisticPose.FaceResults faceResults_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HolisticPose.FaceResults FaceResults {
      get { return faceResults_; }
      set {
        faceResults_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HolisticLandmarks);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HolisticLandmarks other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(PoseLandmarks, other.PoseLandmarks)) return false;
      if (!object.Equals(LeftHandLandmarks, other.LeftHandLandmarks)) return false;
      if (!object.Equals(RightHandLandmarks, other.RightHandLandmarks)) return false;
      if (!object.Equals(FaceResults, other.FaceResults)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (poseLandmarks_ != null) hash ^= PoseLandmarks.GetHashCode();
      if (leftHandLandmarks_ != null) hash ^= LeftHandLandmarks.GetHashCode();
      if (rightHandLandmarks_ != null) hash ^= RightHandLandmarks.GetHashCode();
      if (faceResults_ != null) hash ^= FaceResults.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (poseLandmarks_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(PoseLandmarks);
      }
      if (leftHandLandmarks_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(LeftHandLandmarks);
      }
      if (rightHandLandmarks_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(RightHandLandmarks);
      }
      if (faceResults_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(FaceResults);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (poseLandmarks_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(PoseLandmarks);
      }
      if (leftHandLandmarks_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(LeftHandLandmarks);
      }
      if (rightHandLandmarks_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(RightHandLandmarks);
      }
      if (faceResults_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(FaceResults);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (poseLandmarks_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PoseLandmarks);
      }
      if (leftHandLandmarks_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LeftHandLandmarks);
      }
      if (rightHandLandmarks_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RightHandLandmarks);
      }
      if (faceResults_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FaceResults);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HolisticLandmarks other) {
      if (other == null) {
        return;
      }
      if (other.poseLandmarks_ != null) {
        if (poseLandmarks_ == null) {
          PoseLandmarks = new global::HolisticPose.PoseLandmarks();
        }
        PoseLandmarks.MergeFrom(other.PoseLandmarks);
      }
      if (other.leftHandLandmarks_ != null) {
        if (leftHandLandmarks_ == null) {
          LeftHandLandmarks = new global::HolisticPose.HandLandmarks();
        }
        LeftHandLandmarks.MergeFrom(other.LeftHandLandmarks);
      }
      if (other.rightHandLandmarks_ != null) {
        if (rightHandLandmarks_ == null) {
          RightHandLandmarks = new global::HolisticPose.HandLandmarks();
        }
        RightHandLandmarks.MergeFrom(other.RightHandLandmarks);
      }
      if (other.faceResults_ != null) {
        if (faceResults_ == null) {
          FaceResults = new global::HolisticPose.FaceResults();
        }
        FaceResults.MergeFrom(other.FaceResults);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (poseLandmarks_ == null) {
              PoseLandmarks = new global::HolisticPose.PoseLandmarks();
            }
            input.ReadMessage(PoseLandmarks);
            break;
          }
          case 18: {
            if (leftHandLandmarks_ == null) {
              LeftHandLandmarks = new global::HolisticPose.HandLandmarks();
            }
            input.ReadMessage(LeftHandLandmarks);
            break;
          }
          case 26: {
            if (rightHandLandmarks_ == null) {
              RightHandLandmarks = new global::HolisticPose.HandLandmarks();
            }
            input.ReadMessage(RightHandLandmarks);
            break;
          }
          case 34: {
            if (faceResults_ == null) {
              FaceResults = new global::HolisticPose.FaceResults();
            }
            input.ReadMessage(FaceResults);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (poseLandmarks_ == null) {
              PoseLandmarks = new global::HolisticPose.PoseLandmarks();
            }
            input.ReadMessage(PoseLandmarks);
            break;
          }
          case 18: {
            if (leftHandLandmarks_ == null) {
              LeftHandLandmarks = new global::HolisticPose.HandLandmarks();
            }
            input.ReadMessage(LeftHandLandmarks);
            break;
          }
          case 26: {
            if (rightHandLandmarks_ == null) {
              RightHandLandmarks = new global::HolisticPose.HandLandmarks();
            }
            input.ReadMessage(RightHandLandmarks);
            break;
          }
          case 34: {
            if (faceResults_ == null) {
              FaceResults = new global::HolisticPose.FaceResults();
            }
            input.ReadMessage(FaceResults);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class PoseLandmarks : pb::IMessage<PoseLandmarks>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PoseLandmarks> _parser = new pb::MessageParser<PoseLandmarks>(() => new PoseLandmarks());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PoseLandmarks> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HolisticPose.HolisticLandmarksReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PoseLandmarks() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PoseLandmarks(PoseLandmarks other) : this() {
      landmarks_ = other.landmarks_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PoseLandmarks Clone() {
      return new PoseLandmarks(this);
    }

    /// <summary>Field number for the "landmarks" field.</summary>
    public const int LandmarksFieldNumber = 1;
    private static readonly pb::FieldCodec<global::HolisticPose.Landmark> _repeated_landmarks_codec
        = pb::FieldCodec.ForMessage(10, global::HolisticPose.Landmark.Parser);
    private readonly pbc::RepeatedField<global::HolisticPose.Landmark> landmarks_ = new pbc::RepeatedField<global::HolisticPose.Landmark>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::HolisticPose.Landmark> Landmarks {
      get { return landmarks_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PoseLandmarks);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PoseLandmarks other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!landmarks_.Equals(other.landmarks_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= landmarks_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      landmarks_.WriteTo(output, _repeated_landmarks_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      landmarks_.WriteTo(ref output, _repeated_landmarks_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += landmarks_.CalculateSize(_repeated_landmarks_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PoseLandmarks other) {
      if (other == null) {
        return;
      }
      landmarks_.Add(other.landmarks_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            landmarks_.AddEntriesFrom(input, _repeated_landmarks_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            landmarks_.AddEntriesFrom(ref input, _repeated_landmarks_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the PoseLandmarks message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum LandmarkIndex {
        [pbr::OriginalName("nose")] Nose = 0,
        [pbr::OriginalName("leftEyeInner")] LeftEyeInner = 1,
        [pbr::OriginalName("leftEye")] LeftEye = 2,
        [pbr::OriginalName("leftEyeOuter")] LeftEyeOuter = 3,
        [pbr::OriginalName("rightEyeInner")] RightEyeInner = 4,
        [pbr::OriginalName("rightEye")] RightEye = 5,
        [pbr::OriginalName("rightEyeOuter")] RightEyeOuter = 6,
        [pbr::OriginalName("leftEar")] LeftEar = 7,
        [pbr::OriginalName("rightEar")] RightEar = 8,
        [pbr::OriginalName("mouthLeft")] MouthLeft = 9,
        [pbr::OriginalName("mouthRight")] MouthRight = 10,
        [pbr::OriginalName("leftShoulder")] LeftShoulder = 11,
        [pbr::OriginalName("rightShoulder")] RightShoulder = 12,
        [pbr::OriginalName("leftElbow")] LeftElbow = 13,
        [pbr::OriginalName("rightElbow")] RightElbow = 14,
        [pbr::OriginalName("leftWrist")] LeftWrist = 15,
        [pbr::OriginalName("rightWrist")] RightWrist = 16,
        [pbr::OriginalName("leftPinky")] LeftPinky = 17,
        [pbr::OriginalName("rightPinky")] RightPinky = 18,
        [pbr::OriginalName("leftIndex")] LeftIndex = 19,
        [pbr::OriginalName("rightIndex")] RightIndex = 20,
        [pbr::OriginalName("leftThumb")] LeftThumb = 21,
        [pbr::OriginalName("rightThumb")] RightThumb = 22,
        [pbr::OriginalName("leftHip")] LeftHip = 23,
        [pbr::OriginalName("rightHip")] RightHip = 24,
        [pbr::OriginalName("leftKnee")] LeftKnee = 25,
        [pbr::OriginalName("rightKnee")] RightKnee = 26,
        [pbr::OriginalName("leftAnkle")] LeftAnkle = 27,
        [pbr::OriginalName("rightAnkle")] RightAnkle = 28,
        [pbr::OriginalName("leftHeel")] LeftHeel = 29,
        [pbr::OriginalName("rightHeel")] RightHeel = 30,
        [pbr::OriginalName("leftFootIndex")] LeftFootIndex = 31,
        [pbr::OriginalName("rightFootIndex")] RightFootIndex = 32,
      }

    }
    #endregion

  }

  public sealed partial class HandLandmarks : pb::IMessage<HandLandmarks>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HandLandmarks> _parser = new pb::MessageParser<HandLandmarks>(() => new HandLandmarks());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HandLandmarks> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HolisticPose.HolisticLandmarksReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HandLandmarks() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HandLandmarks(HandLandmarks other) : this() {
      landmarks_ = other.landmarks_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HandLandmarks Clone() {
      return new HandLandmarks(this);
    }

    /// <summary>Field number for the "landmarks" field.</summary>
    public const int LandmarksFieldNumber = 1;
    private static readonly pb::FieldCodec<global::HolisticPose.Landmark> _repeated_landmarks_codec
        = pb::FieldCodec.ForMessage(10, global::HolisticPose.Landmark.Parser);
    private readonly pbc::RepeatedField<global::HolisticPose.Landmark> landmarks_ = new pbc::RepeatedField<global::HolisticPose.Landmark>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::HolisticPose.Landmark> Landmarks {
      get { return landmarks_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HandLandmarks);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HandLandmarks other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!landmarks_.Equals(other.landmarks_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= landmarks_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      landmarks_.WriteTo(output, _repeated_landmarks_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      landmarks_.WriteTo(ref output, _repeated_landmarks_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += landmarks_.CalculateSize(_repeated_landmarks_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HandLandmarks other) {
      if (other == null) {
        return;
      }
      landmarks_.Add(other.landmarks_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            landmarks_.AddEntriesFrom(input, _repeated_landmarks_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            landmarks_.AddEntriesFrom(ref input, _repeated_landmarks_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the HandLandmarks message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum LandmarkIndex {
        [pbr::OriginalName("wrist")] Wrist = 0,
        [pbr::OriginalName("thumbCMC")] ThumbCmc = 1,
        [pbr::OriginalName("thumbMCP")] ThumbMcp = 2,
        [pbr::OriginalName("thumbIP")] ThumbIp = 3,
        [pbr::OriginalName("thumbTIP")] ThumbTip = 4,
        [pbr::OriginalName("indexFingerMCP")] IndexFingerMcp = 5,
        [pbr::OriginalName("indexFingerPIP")] IndexFingerPip = 6,
        [pbr::OriginalName("indexFingerDIP")] IndexFingerDip = 7,
        [pbr::OriginalName("indexFingerTIP")] IndexFingerTip = 8,
        [pbr::OriginalName("middleFingerMCP")] MiddleFingerMcp = 9,
        [pbr::OriginalName("middleFingerPIP")] MiddleFingerPip = 10,
        [pbr::OriginalName("middleFingerDIP")] MiddleFingerDip = 11,
        [pbr::OriginalName("middleFingerTIP")] MiddleFingerTip = 12,
        [pbr::OriginalName("ringFingerMCP")] RingFingerMcp = 13,
        [pbr::OriginalName("ringFingerPIP")] RingFingerPip = 14,
        [pbr::OriginalName("ringFingerDIP")] RingFingerDip = 15,
        [pbr::OriginalName("ringFingerTIP")] RingFingerTip = 16,
        [pbr::OriginalName("pinkyMCP")] PinkyMcp = 17,
        [pbr::OriginalName("pinkyPIP")] PinkyPip = 18,
        [pbr::OriginalName("pinkyDIP")] PinkyDip = 19,
        [pbr::OriginalName("pinkyTIP")] PinkyTip = 20,
      }

    }
    #endregion

  }

  public sealed partial class FaceResults : pb::IMessage<FaceResults>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FaceResults> _parser = new pb::MessageParser<FaceResults>(() => new FaceResults());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FaceResults> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HolisticPose.HolisticLandmarksReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FaceResults() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FaceResults(FaceResults other) : this() {
      landmarks_ = other.landmarks_.Clone();
      blendshapes_ = other.blendshapes_ != null ? other.blendshapes_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FaceResults Clone() {
      return new FaceResults(this);
    }

    /// <summary>Field number for the "landmarks" field.</summary>
    public const int LandmarksFieldNumber = 1;
    private static readonly pb::FieldCodec<global::HolisticPose.Landmark> _repeated_landmarks_codec
        = pb::FieldCodec.ForMessage(10, global::HolisticPose.Landmark.Parser);
    private readonly pbc::RepeatedField<global::HolisticPose.Landmark> landmarks_ = new pbc::RepeatedField<global::HolisticPose.Landmark>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::HolisticPose.Landmark> Landmarks {
      get { return landmarks_; }
    }

    /// <summary>Field number for the "blendshapes" field.</summary>
    public const int BlendshapesFieldNumber = 2;
    private global::HolisticPose.Blendshapes blendshapes_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HolisticPose.Blendshapes Blendshapes {
      get { return blendshapes_; }
      set {
        blendshapes_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FaceResults);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FaceResults other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!landmarks_.Equals(other.landmarks_)) return false;
      if (!object.Equals(Blendshapes, other.Blendshapes)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= landmarks_.GetHashCode();
      if (blendshapes_ != null) hash ^= Blendshapes.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      landmarks_.WriteTo(output, _repeated_landmarks_codec);
      if (blendshapes_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Blendshapes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      landmarks_.WriteTo(ref output, _repeated_landmarks_codec);
      if (blendshapes_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Blendshapes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += landmarks_.CalculateSize(_repeated_landmarks_codec);
      if (blendshapes_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Blendshapes);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FaceResults other) {
      if (other == null) {
        return;
      }
      landmarks_.Add(other.landmarks_);
      if (other.blendshapes_ != null) {
        if (blendshapes_ == null) {
          Blendshapes = new global::HolisticPose.Blendshapes();
        }
        Blendshapes.MergeFrom(other.Blendshapes);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            landmarks_.AddEntriesFrom(input, _repeated_landmarks_codec);
            break;
          }
          case 18: {
            if (blendshapes_ == null) {
              Blendshapes = new global::HolisticPose.Blendshapes();
            }
            input.ReadMessage(Blendshapes);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            landmarks_.AddEntriesFrom(ref input, _repeated_landmarks_codec);
            break;
          }
          case 18: {
            if (blendshapes_ == null) {
              Blendshapes = new global::HolisticPose.Blendshapes();
            }
            input.ReadMessage(Blendshapes);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Blendshapes : pb::IMessage<Blendshapes>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Blendshapes> _parser = new pb::MessageParser<Blendshapes>(() => new Blendshapes());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Blendshapes> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HolisticPose.HolisticLandmarksReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Blendshapes() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Blendshapes(Blendshapes other) : this() {
      scores_ = other.scores_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Blendshapes Clone() {
      return new Blendshapes(this);
    }

    /// <summary>Field number for the "scores" field.</summary>
    public const int ScoresFieldNumber = 1;
    private static readonly pb::FieldCodec<float> _repeated_scores_codec
        = pb::FieldCodec.ForFloat(10);
    private readonly pbc::RepeatedField<float> scores_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> Scores {
      get { return scores_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Blendshapes);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Blendshapes other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!scores_.Equals(other.scores_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= scores_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      scores_.WriteTo(output, _repeated_scores_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      scores_.WriteTo(ref output, _repeated_scores_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += scores_.CalculateSize(_repeated_scores_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Blendshapes other) {
      if (other == null) {
        return;
      }
      scores_.Add(other.scores_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 13: {
            scores_.AddEntriesFrom(input, _repeated_scores_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10:
          case 13: {
            scores_.AddEntriesFrom(ref input, _repeated_scores_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Blendshapes message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum BlendshapesIndex {
        [pbr::OriginalName("_neutral")] Neutral = 0,
        [pbr::OriginalName("browDownLeft")] BrowDownLeft = 1,
        [pbr::OriginalName("browDownRight")] BrowDownRight = 2,
        [pbr::OriginalName("browInnerUp")] BrowInnerUp = 3,
        [pbr::OriginalName("browOuterUpLeft")] BrowOuterUpLeft = 4,
        [pbr::OriginalName("browOuterUpRight")] BrowOuterUpRight = 5,
        [pbr::OriginalName("cheekPuff")] CheekPuff = 6,
        [pbr::OriginalName("cheekSquintLeft")] CheekSquintLeft = 7,
        [pbr::OriginalName("cheekSquintRight")] CheekSquintRight = 8,
        [pbr::OriginalName("eyeBlinkLeft")] EyeBlinkLeft = 9,
        [pbr::OriginalName("eyeBlinkRight")] EyeBlinkRight = 10,
        [pbr::OriginalName("eyeLookDownLeft")] EyeLookDownLeft = 11,
        [pbr::OriginalName("eyeLookDownRight")] EyeLookDownRight = 12,
        [pbr::OriginalName("eyeLookInLeft")] EyeLookInLeft = 13,
        [pbr::OriginalName("eyeLookInRight")] EyeLookInRight = 14,
        [pbr::OriginalName("eyeLookOutLeft")] EyeLookOutLeft = 15,
        [pbr::OriginalName("eyeLookOutRight")] EyeLookOutRight = 16,
        [pbr::OriginalName("eyeLookUpLeft")] EyeLookUpLeft = 17,
        [pbr::OriginalName("eyeLookUpRight")] EyeLookUpRight = 18,
        [pbr::OriginalName("eyeSquintLeft")] EyeSquintLeft = 19,
        [pbr::OriginalName("eyeSquintRight")] EyeSquintRight = 20,
        [pbr::OriginalName("eyeWideLeft")] EyeWideLeft = 21,
        [pbr::OriginalName("eyeWideRight")] EyeWideRight = 22,
        [pbr::OriginalName("jawForward")] JawForward = 23,
        [pbr::OriginalName("jawLeft")] JawLeft = 24,
        [pbr::OriginalName("jawOpen")] JawOpen = 25,
        [pbr::OriginalName("jawRight")] JawRight = 26,
        [pbr::OriginalName("mouthClose")] MouthClose = 27,
        [pbr::OriginalName("mouthDimpleLeft")] MouthDimpleLeft = 28,
        [pbr::OriginalName("mouthDimpleRight")] MouthDimpleRight = 29,
        [pbr::OriginalName("mouthFrownLeft")] MouthFrownLeft = 30,
        [pbr::OriginalName("mouthFrownRight")] MouthFrownRight = 31,
        [pbr::OriginalName("mouthFunnel")] MouthFunnel = 32,
        [pbr::OriginalName("mouthLeft")] MouthLeft = 33,
        [pbr::OriginalName("mouthLowerDownLeft")] MouthLowerDownLeft = 34,
        [pbr::OriginalName("mouthLowerDownRight")] MouthLowerDownRight = 35,
        [pbr::OriginalName("mouthPressLeft")] MouthPressLeft = 36,
        [pbr::OriginalName("mouthPressRight")] MouthPressRight = 37,
        [pbr::OriginalName("mouthPucker")] MouthPucker = 38,
        [pbr::OriginalName("mouthRight")] MouthRight = 39,
        [pbr::OriginalName("mouthRollLower")] MouthRollLower = 40,
        [pbr::OriginalName("mouthRollUpper")] MouthRollUpper = 41,
        [pbr::OriginalName("mouthShrugLower")] MouthShrugLower = 42,
        [pbr::OriginalName("mouthShrugUpper")] MouthShrugUpper = 43,
        [pbr::OriginalName("mouthSmileLeft")] MouthSmileLeft = 44,
        [pbr::OriginalName("mouthSmileRight")] MouthSmileRight = 45,
        [pbr::OriginalName("mouthStretchLeft")] MouthStretchLeft = 46,
        [pbr::OriginalName("mouthStretchRight")] MouthStretchRight = 47,
        [pbr::OriginalName("mouthUpperUpLeft")] MouthUpperUpLeft = 48,
        [pbr::OriginalName("mouthUpperUpRight")] MouthUpperUpRight = 49,
        [pbr::OriginalName("noseSneerLeft")] NoseSneerLeft = 50,
        [pbr::OriginalName("noseSneerRight")] NoseSneerRight = 51,
        [pbr::OriginalName("tongueOut")] TongueOut = 52,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
